### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by ktdreyer** [dkubb/descendants_tracker#4]
Would you mind tagging and pushing a new version of descendants_tracker to rubygems.org?

The latest version there is quite old (0.0.1), and it would be nice to have a version that works with rspec 2.x.

**Comment by solnic** [comment]
@dkubb @mbj I don't have access so I couldn't push the new version but FWIW I prepared everything for a new release so please push a new gem

**Comment by solnic** [comment]
@ktdreyer looks like new version is available, closing
